apps/demo/urls.py
from django.urls import path

from .views import (
    ListView, 
    CsvDetailedView,
    CsvScriptView, 
    CsvDownloadView,
    NewsView,
    StreamlitView,
)

app_name = "demo"

urlpatterns = [
    path("", ListView.as_view(), name="demo_list"),
    path("csv/", CsvDetailedView.as_view(), name="demo_csv"),
    path("csv/script/", CsvScriptView.as_view(), name="demo_script"),
    path("csv/download/", CsvDownloadView.as_view(), name="demo_download"),
    path("news/", NewsView.as_view(), name="demo_news"),
    # do you want other weather api urls?
    path('streamlit/', StreamlitView.as_view(), name='demo_streamlit'),
]

general_balance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.teams.urls import team_urlpatterns as single_team_urls
from apps.web.urls import team_urlpatterns as web_team_urls
from apps.web.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap(),
}

# urls that are unique to using a team should go here
team_urlpatterns = [
    path("", include(web_team_urls)),
    path("team/", include(single_team_urls)),
    path("example/", include("apps.teams_example.urls")),
]

urlpatterns = [
    # redirect Django admin login to main login page
    path("admin/login/", RedirectView.as_view(pattern_name="account_login")),
    path("admin/", admin.site.urls),
    path("amwell/", include("apps.amwell.urls")), # KH - added this line
    path("demo/", include("apps.demo.urls")), # KH - added this line
    path("dashboard/", include("apps.dashboard.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("a/<slug:team_slug>/", include(team_urlpatterns)),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("teams/", include("apps.teams.urls")),
    path("", include("apps.web.urls")),
    path("support/", include("apps.support.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # API docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI - you may wish to remove one of these depending on your preference
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # hijack urls for impersonation
    path("hijack/", include("hijack.urls", namespace="hijack")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/demo/models.py
from django.db import models

class CsvTask(models.Model):
    csv_file = models.FileField(upload_to='static/demo/csv_task/')
    excel_file = models.FileField(upload_to='static/demo/csv_task/')
    updated_excel_file = models.FileField(upload_to='static/demo/csv_task/', blank=True, null=True)
    csv_file_uploaded_at = models.DateTimeField(auto_now_add=True)
    excel_file_uploaded_at = models.DateTimeField(auto_now_add=True)
    python_script_success = models.BooleanField(default=False)

    def __str__(self):
        return f"CSV: {self.csv_file.name}, Excel: {self.excel_file.name}"

apps/demo/forms.py
from django import forms
from .models import CsvTask

class CsvFileForm(forms.ModelForm):
    class Meta:
        model = CsvTask
        fields = ['csv_file']

class ExcelFileForm(forms.ModelForm):
    class Meta:
        model = CsvTask
        fields = ['excel_file']
        

apps/demo/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, View, FormView, TemplateView
from django.shortcuts import redirect
import requests
import os
import subprocess
import glob

from .models import CsvTask
from .forms import CsvFileForm, ExcelFileForm


class ListView(ListView):
    template_name = "demo/demo_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['csv_file'] = CsvTask.objects.all()
        context['excel_file'] = CsvTask.objects.all()
        return context

    def get_queryset(self):
        return CsvTask.objects.all()
    
class CsvDetailedView(FormView):
    template_name = "demo/demo_csv.html"
    form_class = CsvFileForm
    excel_form_class = ExcelFileForm
    success_url = '/demo/csv/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        file_instance = CsvTask.objects.last()
        context.update({
            'excel_form': self.excel_form_class(self.request.POST or None, self.request.FILES or None),
            'file': file_instance,
            'show_run_script': self.request.session.pop('show_run_script', False),
            'script_executed': self.request.session.pop('script_executed', False),
            'download_file_name': os.path.basename(file_instance.updated_excel_file.name) 
            if file_instance and file_instance.updated_excel_file else None,
        })
        return context
    
    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.form_class
        return super().get_form(form_class)
    
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        excel_form = self.excel_form_class(self.request.POST, self.request.FILES)
        if form.is_valid() and excel_form.is_valid():
            return self.form_valid(form, excel_form)
        else:
            return self.form_invalid(form, excel_form)
    
    def form_valid(self, form, excel_form):
        form.save()
        excel_form.save()
        messages.success(self.request, "Files uploaded successfully")
        self.request.session['show_run_script'] = True
        return super().form_valid(form)
    
    def form_invalid(self, form, excel_form):
        return self.render_to_response(self.get_context_data(form=form, excel_form=excel_form))
    

class CsvScriptView(View):
    def post(self, request, *args, **kwargs):
        file_instance = CsvTask.objects.filter(
            csv_file__isnull=False, 
            excel_file__isnull=False).last()
    
        if not file_instance:
            messages.error(request, "Please upload both CSV and Excel files first")
            return redirect('demo:demo_csv')
        
        base_dir = os.path.join(settings.MEDIA_ROOT, 'static', 'demo', 'csv_task')
        script_path = os.path.join(base_dir, 'sandbox1.py')
        csv_file = os.path.join(base_dir, os.path.basename(file_instance.csv_file.name))
        excel_file = os.path.join(base_dir, os.path.basename(file_instance.excel_file.name))

        if not os.path.exists(script_path):
            messages.error(request, "Script not found")
            return redirect('demo:demo_csv')
        
        try:
            env = os.environ.copy()
            env['DJANGO_SETTINGS_MODULE'] = 'general_balance.settings'

            result = subprocess.run(
                ['python', script_path, csv_file, excel_file], 
                check=True, 
                env=env, 
                capture_output=True, 
                text=True,
                )
            if result.returncode == 0:
                messages.success(request, "Script executed successfully")
                excel_files = glob.glob(os.path.join(base_dir, '*.xlsx'))
                if excel_files:
                    most_recent_excel_path = max(excel_files, key=os.path.getctime)
                    file_instance.updated_excel_file = os.path.relpath(most_recent_excel_path, settings.MEDIA_ROOT)
                    file_instance.python_script_success = True
                    file_instance.save()
                    request.session['downloadable_file'] = most_recent_excel_path
                else:
                    if 'downloadable_file' in request.session:
                        del request.session['downloadable_file']
            else:
                messages.error(request, 'Error while executing script')
        except subprocess.CalledProcessError as e:
            messages.error(request, f'Error while executing script: {e}')
        except Exception as e:
            messages.error(request, f'An unexpected error occurred: {e}')

        return redirect('demo:demo_csv')
    
class CsvDownloadView(View):
    def get(self, request, *args, **kwargs):
        file_path = request.session.get('downloadable_file')
        if file_path and os.path.isfile(file_path):
            try:
                with open(file_path, 'rb') as file:
                    response = HttpResponse(file.read(), content_type='application/vnd.ms-excel')
                    file_name = os.path.basename(file_path)
                    response['Content-Disposition'] = f'attachment; filename={file_name}'
                    return response
            except IOError:
                messages.error(request, 'Error opening file')
        else:
            messages.error(request, 'No updated excel file found')
        return redirect('demo:demo_csv')
    

# weather api

class NewsView(TemplateView):
    template_name = "demo/news.html"

    def get_top_story(self):
        api_key = os.getenv('NYTIMES_API_KEY')  # see .env.example file
        url = f"https://api.nytimes.com/svc/mostpopular/v2/viewed/1.json?api-key={api_key}"
        response = requests.get(url)
        data = response.json()

        if data and 'results' in data and len(data['results']) > 0:
            return data['results'][0]  # Return the top viewed story
        else:
            return None
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['top_story'] = self.get_top_story()
        return context



# streamlit view
class StreamlitView(View):
    pass
    

templates/demo/demo_csv.html
{#{% extends "pegasus/examples/examples_base.html" %}#}
{% load static %}
{% block app %}


<!-- Upload CSV file -->
<div class="max-w-3xl mx-auto bg-gray-600 rounded-xl shadow-lg overflow-hidden mt-6">
    <div class="md:flex">
        <div class="p-8 text-white">
            <h2 class="text-2xl font-bold mb-6">Csv copy and paste</h2>

            <!-- Form for file upload -->
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-6">
                    {{ form }}  <!-- Form for uploading CSV files -->
                </div>
                <div class="mb-6">
                    {{ excel_form }}  <!-- Form for uploading Excel files -->
                </div>
                <button class="pg-button-primary" type="submit">Save</button>
            </form>

            <!-- Show the Run Python Script button only if the files have been saved successfully -->
            {% if file and show_run_script %}
            <div class="mt-8">
                <form method="post" action="{% url 'demo:demo_script' %}">
                    {% csrf_token %}
                    <button class="" type="submit">Run Python Script</button>
                </form>
            </div>
            {% endif %}

            <!-- If script executed, show download link in a separate card -->
            {% if file and file.python_script_success %}
            
            <div class="bg-white-700 rounded-lg p-4 shadow mt-10">
                <h4 class="text-lg font-bold mb-2">Download</h4>
                <a href="{% url 'demo:demo_download' %}" class="text-blue-400">{{ download_file_name }}</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/demo/demo_list.html
{% extends "web/app/app_base.html" %}
{% load static %}

{% block app %}
<body class="theme-business">
    <div class="container mx-auto p-6">
        <div class="bg-white p-4 rounded shadow-md">
            <h1 class="text-2xl font-bold text-gray-800 mb-4">Demo</h1>
            <p class="text-gray-700 mb-4">
                This is a generic demo page. Please select an option below.
            </p>
            <div class="carousel">
                <div class="grid grid-cols-2 gap-12">
                    <!-- Card 1 -->
                    <a href="{% url 'demo:demo_csv' %}" class="bg-blue-300 p-4 rounded shadow-md block hover:bg-gray-200 h-auto">
                        <h2 class="text-xl font-bold text-gray-800 mb-2">CSV Import</h2>
                        <p class="text-gray-700 mb-4 overflow-auto h-20">
                            This task will import a csv file and excel template.
                            Then the copy the csv data and paste it into the excel template.
                            Finally, an revised excel template will be available for download.
                        </p>
                    </a>
                    <!-- Card 2 -->
                    <a href="{% url 'demo:demo_news' %}" class="bg-blue-300 p-4 rounded shadow-md block hover:bg-gray-200 h-auto">
                        <h2 class="text-xl font-bold text-gray-800 mb-2">NY Times</h2>
                        <p class="text-gray-700 mb-4 overflow-auto h-20">Description of Card #2.</p>
                    </a>
                    <!-- Card 3 -->
                    <a href="#" class="bg-blue-300 p-4 rounded shadow-md block hover:bg-gray-200 h-auto">
                        <h2 class="text-xl font-bold text-gray-800 mb-2">Steamlit</h2>
                        <p class="text-gray-700 mb-4 overflow-auto h-20">Description of Card #3.</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

templates/demo/news.html
{#{% extends "pegasus/examples/examples_base.html" %}#}
{% load static %}
{% block app %}

<h1>Top News</h1>

{% if top_story %}
    <h2>{{ top_story.title }}</h2>
    <p>{{ top_story.abstract }}</p>
    <a href="{{ top_story.url }}">Read more</a>
{% else %}
    <p>No top story found.</p>
{% endif %}


{% endblock %}