apps/amwell/urls.py
from django.urls import path

from .views import AmwellListView, BankRecView, BankRecScriptView, BankRecDownloadView

app_name = "amwell"

urlpatterns = [
    path("", AmwellListView.as_view(), name="list"),
    path("bank_rec/", BankRecView.as_view(), name="bank_rec"),
    path("bank_rec/script/", BankRecScriptView.as_view(), name="bank_rec_script"),
    path("bank_rec/download/", BankRecDownloadView.as_view(), name="bank_rec_download"),
]

general_balance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.teams.urls import team_urlpatterns as single_team_urls
from apps.web.urls import team_urlpatterns as web_team_urls
from apps.web.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap(),
}

# urls that are unique to using a team should go here
team_urlpatterns = [
    path("", include(web_team_urls)),
    path("team/", include(single_team_urls)),
    path("example/", include("apps.teams_example.urls")),
]

urlpatterns = [
    # redirect Django admin login to main login page
    path("admin/login/", RedirectView.as_view(pattern_name="account_login")),
    path("admin/", admin.site.urls),
    path("amwell/", include("apps.amwell.urls")), # KH - added this line
    path("demo/", include("apps.demo.urls")), # KH - added this line
    path("dashboard/", include("apps.dashboard.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("a/<slug:team_slug>/", include(team_urlpatterns)),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("teams/", include("apps.teams.urls")),
    path("", include("apps.web.urls")),
    path("support/", include("apps.support.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # API docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI - you may wish to remove one of these depending on your preference
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # hijack urls for impersonation
    path("hijack/", include("hijack.urls", namespace="hijack")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/amwell/models.py
from django.db import models


class BankRec(models.Model):
    csv_file = models.FileField(upload_to='static/bank_rec/')
    excel_file = models.FileField(upload_to='static/bank_rec/')
    updated_excel_file = models.FileField(upload_to='static/bank_rec/', blank=True, null=True)
    csv_file_uploaded_at = models.DateTimeField(auto_now_add=True)
    excel_file_uploaded_at = models.DateTimeField(auto_now_add=True)
    python_script_success = models.BooleanField(default=False)

    def __str__(self):
        return f"CSV: {self.csv_file.name}, Excel: {self.excel_file.name}"

    class Meta:
        app_label = 'amwell'

apps/amwell/forms.py
from django import forms
from .models import BankRec

class CsvFileForm(forms.ModelForm):
    class Meta:
        model = BankRec
        fields = ['csv_file']

class ExcelFileForm(forms.ModelForm):
    class Meta:
        model = BankRec
        fields = ['excel_file']

apps/amwell/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.views.generic import ListView, View, FormView
from django.shortcuts import redirect
import os
import subprocess
import glob

from .models import BankRec
from .forms import CsvFileForm, ExcelFileForm


class AmwellListView(ListView):
    template_name = "amwell/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['csv_file'] = BankRec.objects.all()
        context['excel_file'] = BankRec.objects.all()
        return context

    def get_queryset(self):
        return BankRec.objects.all()  

class BankRecView(FormView):
    template_name = "amwell/bank_rec.html"
    form_class = CsvFileForm
    excel_form_class = ExcelFileForm
    success_url = '/amwell/bank_rec/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        file_instance = BankRec.objects.last()  # Get the most recent file
        context.update({
            'excel_form': self.excel_form_class(self.request.POST or None, self.request.FILES or None),
            'file': file_instance,
            'show_run_script': self.request.session.pop('show_run_script', False),
            'script_executed': self.request.session.pop('script_executed', False),
            'download_file_name': os.path.basename(file_instance.updated_excel_file.name) 
            if file_instance and file_instance.updated_excel_file else None,
        })
        return context
    
    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.form_class
        return super().get_form(form_class)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        excel_form = self.excel_form_class(self.request.POST, self.request.FILES)
        if form.is_valid() and excel_form.is_valid():
            return self.form_valid(form, excel_form)
        else:
            return self.form_invalid(form, excel_form)

    def form_valid(self, form, excel_form):
        form.save()
        excel_form.save()
        messages.success(self.request, 'Files uploaded successfully')
        self.request.session['show_run_script'] = True
        return super().form_valid(form)

    def form_invalid(self, form, excel_form):
        return self.render_to_response(self.get_context_data(form=form, excel_form=excel_form))


class BankRecScriptView(View):
    def post(self, request, *args, **kwargs):
        file_instance = BankRec.objects.filter(
            csv_file__isnull=False, 
            excel_file__isnull=False).last()

        if not file_instance:
            messages.error(request, "No files uploaded.")
            return redirect('amwell:bank_rec')

        base_dir = os.path.join(settings.MEDIA_ROOT, 'static', 'amwell_bank_rec')  # Ensure the correct base directory
        script_path = os.path.join(base_dir, 'amwell_bank_rec.py')
        csv_file_path = os.path.join(base_dir, os.path.basename(file_instance.csv_file.name))  # Ensure full path to CSV file
        excel_file_path = os.path.join(base_dir, os.path.basename(file_instance.excel_file.name))  # Ensure full path to Excel file

        print("CSV File Path:", csv_file_path)
        print("Excel File Path:", excel_file_path)
        print("Script Path:", script_path)

        if not os.path.isfile(script_path):
            messages.error(request, f'Script file not found: {script_path}')
            return redirect('amwell:bank_rec')

        try:
            env = os.environ.copy()
            env['DJANGO_SETTINGS_MODULE'] = 'general_balance.settings'

            # Print the Python script being run
            print("Running Python script:", script_path)

            result = subprocess.run(['python', script_path, csv_file_path, excel_file_path], 
                                    check=True, 
                                    env=env, 
                                    capture_output=True, 
                                    text=True,
                                    )
            
            print("Subprocess STDOUT:", result.stdout)
            print("Subprocess STDERR:", result.stderr)

            if result.returncode == 0:
                messages.success(request, 'Script executed successfully')
                excel_files = glob.glob(os.path.join(base_dir, '*.xlsx'))
                if excel_files:
                    most_recent_excel_path = max(excel_files, key=os.path.getctime)
                    file_instance.updated_excel_file = os.path.relpath(most_recent_excel_path, settings.MEDIA_ROOT)
                    file_instance.python_script_success = True
                    file_instance.save()
                    request.session['downloadable_file'] = most_recent_excel_path
                else:
                    if 'downloadable_file' in request.session:
                        del request.session['downloadable_file']
            else:
                messages.error(request, 'Error while executing script')
        except subprocess.CalledProcessError as e:
            messages.error(request, f'Error while executing script: {e}')
        except Exception as e:
            messages.error(request, f'An unexpected error occurred: {e}')

        return redirect('amwell:bank_rec')





class BankRecDownloadView(View):
    def get(self, request, *args, **kwargs):
        file_path = request.session.get('downloadable_file')
        if file_path and os.path.isfile(file_path):
            try:
                with open(file_path, 'rb') as file:
                    response = HttpResponse(file.read(), content_type='application/vnd.ms-excel')
                    file_name = os.path.basename(file_path)
                    response['Content-Disposition'] = f'attachment; filename={file_name}'
                    return response
            except IOError:
                messages.error(request, 'Error opening file')
        else:
            messages.error(request, 'No updated excel file found')
        return redirect('amwell:bank_rec')

'''OLD'''
# class BankRecScriptView(View):
#     def post(self, request, *args, **kwargs):
#         # Check if there are files uploaded
#         file_instance = BankRec.objects.filter(csv_file__isnull=False, excel_file__isnull=False).last()
        
#         if not file_instance:
#             messages.error(request, "No files uploaded.")
#             return redirect('amwell:bank_rec')

#         # Define paths
#         base_dir = os.path.join(settings.BASE_DIR, 'media', 'static', 'bank_rec')
#         script_path = os.path.join(base_dir, 'sandbox1.py')  # sandbox1.py is the script file
#         csv_file_path = os.path.join(base_dir, file_instance.csv_file.name)  # csv_file is a FileField
#         excel_file_path = os.path.join(base_dir, file_instance.excel_file.name) # excel_file is a FileField
        
#         print("CSV File Path:", csv_file_path)
#         print("Excel File Path:", excel_file_path)


#         # Check if script file exists
#         if not os.path.isfile(script_path):
#             messages.error(request, f'Script file not found: {script_path}')
#             return redirect('amwell:bank_rec')
        
#         # Run the script
#         try:
#             result = subprocess.run(['python', script_path, csv_file_path, excel_file_path],
#                                      check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
#             print("STDOUT:", result.stdout.decode())
#             print("STDERR:", result.stderr.decode())

#             if result.returncode == 0:
#                 messages.success(request, 'Script executed successfully')
#                 # Assuming script modifies the existing Excel file or creates a new one in the same path
#                 relative_path = os.path.join('static', 'bank_rec', os.path.basename(excel_file_path))
#                 file_instance.updated_excel_file = relative_path
#                 # create or update the updated_excel_file filefield in model
#                 #file_instance.updated_excel_file = excel_file_path 
#                 file_instance.python_script_success = True # update model
#                 file_instance.save()
#                 self.request.session['script_executed'] = True
#                 request.session['download_file'] = str(file_instance.updated_excel_file)
#             else:
#                 messages.error(request, 'Error while executing script')
#         except subprocess.CalledProcessError as e:
#             messages.error(request, f'Error while executing script: {e}')
#         except Exception as e:
#             messages.error(request, f'An unexpected error occurred: {e}')

#         return redirect('amwell:bank_rec')

# class BankRecDownloadView(View):
#     def get (self, request, *args, **kwargs):
#         file_path = request.session.get('download_file')
#         if file_path and os.path.isfile(file_path):
#             try:
#                 with open(file_path, 'rb') as file:
#                     response = HttpResponse(file.read(), content_type='application/vnd.ms-excel')
#                     file_name = os.path.basename(file_path)  # Get the file name
#                     response['Content-Disposition'] = f'attachment; filename={file_name}'
#                     return response
#             except IOError:
#                 messages.error(request, 'Error opening file')
#         else:
#             messages.error(request, 'No updated excel file found')
#         return render(request, 'amwell/bank_rec.html')

templates/amwell/bank_rec.html
{#{% extends "pegasus/examples/examples_base.html" %}#}
{% load static %}


<head>
        <title>Bank Rec</title>
</head>
 
{% block app %}

<!-- Upload CSV file -->
<div class="max-w-3xl mx-auto bg-gray-600 rounded-xl shadow-lg overflow-hidden mt-6">
    <div class="md:flex">
        <div class="p-8 text-white">
            <h2 class="text-2xl font-bold mb-6">Bank Reconciliation</h2>

            <!-- Form for file upload -->
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-6">
                    {{ form }}  <!-- Form for uploading CSV files -->
                </div>
                <div class="mb-6">
                    {{ excel_form }}  <!-- Form for uploading Excel files -->
                </div>
                <button class="" type="submit">Save</button>
            </form>

            <!-- Show the Run Python Script button only if the files have been saved successfully -->
            {% if file and show_run_script %}
            <div class="mt-8">
                <form method="post" action="{% url 'amwell:bank_rec_script' %}">
                    {% csrf_token %}
                    <button class="" type="submit">Run Python Script</button>
                </form>
            </div>
            {% endif %}

            <!-- If script executed, show download link in a separate card -->
            {% if file and file.python_script_success %}
            
            <div class="bg-white-700 rounded-lg p-4 shadow mt-10">
                <h4 class="text-lg font-bold mb-2">Download</h4>
                <a href="{% url 'amwell:bank_rec_download' %}" class="text-blue-400">{{ download_file_name }}</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/amwell/bankrec.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}

<head>
        <title>Bank Rec</title>
</head>
 
{% block app %}

<!-- Display messages -->
{% if messages %}
    <div class="mb-6">
        {% for message in messages %}
        <div class="{% if message.tags %}alert {{ message.tags }}{% endif %}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
{% endif %}

<!-- Upload CSV file -->
<div class="max-w-3xl mx-auto bg-gray-600 rounded-xl shadow-lg overflow-hidden mt-6">
    <div class="md:flex">
        <div class="p-8 text-white">
            <h2 class="text-2xl font-bold mb-6">Bank Reconciliation</h2>

            <!-- Form for file upload -->
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-6">
                    {{ csv_form }}  <!-- Form for uploading CSV files -->
                </div>
                <div class="mb-6">
                    {{ excel_form }}  <!-- Form for uploading Excel files -->
                </div>
                <button class="bg-blue-600 hover:bg-blue-800 text-white font-bold py-2 px-6 rounded" type="submit">Save</button>
            </form>

            <!-- Show the Run Python Script button only if the files have been saved successfully -->
            {% if file and show_run_script %}
            <div class="mt-8">
                <form method="post" action="{% url 'bankrec:bank_rec_script' %}">
                    {% csrf_token %}
                    <button class="bg-blue-600 hover:bg-blue-800 text-white font-bold py-2 px-6 rounded" type="submit">Run Python Script</button>
                </form>
            </div>
            {% endif %}

            <!-- If script executed, show download link in a separate card -->
            {% if file and script_executed %}
            <div class="bg-gray-700 rounded-lg p-4 shadow mt-10">
                <h4 class="text-lg font-bold mb-2">Download</h4>
                <a href="{% url 'bankrec:bank_rec_download' %}" class="text-blue-400">{{ file.excel.name }}</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/amwell/list.html
{#{% extends "pegasus/examples/examples_base.html" %}#}
{% extends "web/app/app_base.html" %}

{% load static %}

<head>
    <title>Dashboard</title>
</head>
 
{% block app %}
<body class="theme-business">
    <div class="container mx-auto p-6">
        <div class="bg-white p-4 rounded shadow-md">
            <h1 class="text-2xl font-bold text-gray-800 mb-4">Dashboard</h1>
            <p class="text-gray-700 mb-4">
                Welcome to the amwell's Dashboard of automations. Please select an option below.
            </p>
            <div class="carousel">
                <div class="flex overflow-x-auto space-x-4">
                    <!-- Card 1 -->
                    <a href="{% url 'amwell:bank_rec' %}" class="min-w-[300px] bg-blue-300 p-4 rounded shadow-md block hover:bg-gray-200">
                        <h2 class="text-xl font-bold text-gray-800 mb-2">Bank Rec</h2>
                        <p class="text-gray-700 mb-4">Description of Bank Rec.</p>
                    </a>
                    <!-- Add more cards following this pattern -->
                    <!-- Card 2 -->
                    <a href="#" class="min-w-[300px] bg-blue-300 p-4 rounded shadow-md block hover:bg-gray-200">
                        <h2 class="text-xl font-bold text-gray-800 mb-2">Card Title #2</h2>
                        <p class="text-gray-700 mb-4">Description of Card #2.</p>
                    </a>
                    <!-- Repeat for additional cards -->
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}