apps/teams_example/urls.py
from django.urls import path

from . import views

app_name = "teams_example"

urlpatterns = [
    path("", views.PlayerListView.as_view(), name="player_list"),
    path("new/", views.PlayerCreateView.as_view(), name="player_create"),
    path("<int:pk>/", views.PlayerDetailView.as_view(), name="player_detail"),
    path("<int:pk>/update/", views.PlayerUpdateView.as_view(), name="player_update"),
    path("<int:pk>/delete/", views.PlayerDeleteView.as_view(), name="player_delete"),
]

general_balance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.teams.urls import team_urlpatterns as single_team_urls
from apps.web.urls import team_urlpatterns as web_team_urls
from apps.web.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap(),
}

# urls that are unique to using a team should go here
team_urlpatterns = [
    path("", include(web_team_urls)),
    path("team/", include(single_team_urls)),
    path("example/", include("apps.teams_example.urls")),
]

urlpatterns = [
    # redirect Django admin login to main login page
    path("admin/login/", RedirectView.as_view(pattern_name="account_login")),
    path("admin/", admin.site.urls),
    path("amwell/", include("apps.amwell.urls")), # KH - added this line
    path("demo/", include("apps.demo.urls")), # KH - added this line
    path("dashboard/", include("apps.dashboard.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("a/<slug:team_slug>/", include(team_urlpatterns)),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("teams/", include("apps.teams.urls")),
    path("", include("apps.web.urls")),
    path("support/", include("apps.support.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # API docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI - you may wish to remove one of these depending on your preference
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # hijack urls for impersonation
    path("hijack/", include("hijack.urls", namespace="hijack")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/teams_example/models.py
from django.db import models
from django.urls import reverse

from apps.teams.models import BaseTeamModel


class Player(BaseTeamModel):
    """
    A player is part of a team.

    Note that it inherits from BaseTeamModel which handles the team relationship.
    """

    SEX_CHOICES = (
        ("m", "Male"),
        ("f", "Female"),
    )
    name = models.CharField(max_length=100)
    sex = models.CharField(max_length=10, blank=True, choices=SEX_CHOICES)
    date_of_birth = models.DateField(null=True, blank=True, help_text="E.g. 1979-05-12")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("teams_example:player_detail", kwargs={"team_slug": self.team.slug, "pk": self.pk})

apps/teams_example/forms.py
from django import forms

from apps.teams_example.models import Player


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ["name", "sex", "date_of_birth"]

apps/teams_example/views.py
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.utils.translation import gettext_lazy as _

from .forms import PlayerForm
from .models import Player
from ..teams.mixins import LoginAndTeamRequiredMixin


class PlayerViewMixin(LoginAndTeamRequiredMixin):
    """
    Mixin class for all views in the example app.
    """

    model = Player

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active_tab"] = "teams_example"
        context["page_title"] = _("Example App | {team}").format(team=self.request.team)
        return context


class PlayerListView(PlayerViewMixin, ListView):
    pass


class PlayerCreateView(PlayerViewMixin, CreateView):
    form_class = PlayerForm

    def form_valid(self, form):
        form.instance.team = self.request.team
        return super().form_valid(form)


class PlayerDetailView(PlayerViewMixin, DetailView):
    pass


class PlayerUpdateView(PlayerViewMixin, UpdateView):
    form_class = PlayerForm


class PlayerDeleteView(PlayerViewMixin, DeleteView):
    def get_success_url(self):
        return reverse("teams_example:player_list", args=[self.request.team.slug])

templates/teams_example/player_confirm_delete.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% load form_tags %}
{% block app %}
<nav aria-label="breadcrumbs">
  <ul class="pg-breadcrumbs">
    <li><a href="{% url 'teams_example:player_list' request.team.slug %}">Players</a></li>
    <li><a href="{{ player.get_absolute_url }}">{{ player.name }}</a></li>
    <li class="pg-breadcrumb-active" aria-current="page">Delete</li>
  </ul>
</nav>
<section class="app-card">
  <h3 class="pg-subtitle">Confirm Delete</h3>
  <form method="post">{% csrf_token %}
    <p>
      Are you sure you want to delete <strong>{{ player }}</strong>?
      This action cannot be undone.
    </p>
    <div class="mt-2">
      <input type="submit" class="pg-button-danger" value="Delete">
    </div>
  </form>
</section>
{% endblock %}

templates/teams_example/player_detail.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% block app %}
<nav aria-label="breadcrumbs">
  <ol class="pg-breadcrumbs">
    <li class=""><a href="{% url 'teams_example:player_list' request.team.slug %}">Players</a></li>
    <li class="pg-breadcrumb-active" aria-current="page">{{ player.name }}</li>
  </ol>
</nav>
<section class="app-card">
  <h3 class="pg-subtitle">Detail view for {{ player.name }}</h3>
  <p>You can use this page to show any information you want to about {{ player.name }}.</p>
  <p class="mt-2">
    For example, their sex is <strong>{{ player.get_sex_display|lower }}</strong>,
    and they were born on <strong>{{ player.date_of_birth }}</strong>.
  </p>
  <p class="mt-2">You can edit this information by clicking the button below.</p>
  <div class="mt-2">
    <a href="{% url 'teams_example:player_update' request.team.slug player.pk %}" class="pg-button-secondary">
      <span class="pg-icon"><i class="fa fa-pencil"></i></span>
      <span>Edit</span>
    </a>
    <a href="{% url 'teams_example:player_delete' request.team.slug player.pk %}" class="pg-button-danger">
      <span class="pg-icon"><i class="fa fa-times"></i></span>
      <span>Delete</span>
    </a>
  </div>
</section>
{% endblock %}

templates/teams_example/player_form.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% load form_tags %}
{% block app %}
<nav aria-label="breadcrumbs">
  <ol class="pg-breadcrumbs">
    <li><a href="{% url 'teams_example:player_list' request.team.slug %}">Players</a></li>
    {% if player %}
    <li><a href="{{ player.get_absolute_url }}">{{ player.name }}</a></li>
    <li class="pg-breadcrumb-active" aria-current="page">Edit</li>
    {% else %}
    <li class="pg-breadcrumb-active" aria-current="page">New</li>
    {% endif %}
  </ol>
</nav>
<section class="app-card">
  <h3 class="pg-subtitle">{% if player %}Edit {{ player.name }}{% else %}New Player{% endif %}</h3>
  <form method="post">{% csrf_token %}
      {% render_form_fields form %}
      <input type="submit" class="pg-button-primary" value="Save">

  </form>
</section>
{% endblock %}

templates/teams_example/player_list.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% block app %}
<section class="app-card">
  <h3 class="pg-subtitle">The Example Teams App</h3>
  <p>
    This is a create-read-update-delete (CRUD) example of objects&mdash;Players&mdash;that belong to a team.
    It use Django's <a href="https://docs.djangoproject.com/en/3.2/topics/class-based-views/generic-display/">built-in class-based views</a>
    and Pegasus's built-in helpers to scope all model access to team members.
    It is provided to quickly demonstrate how to create and use a model associated with Teams.
    The code is in <code>apps/teams_example</code>.
  </p>
</section>
<section class="app-card">
  <h3 class="pg-subtitle">All Players</h3>
  {% for player in object_list %}
    {% if forloop.first %}
    <div class='table-responsive'>
      <table class="table pg-table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Sex</th>
          <th>Date of Birth</th>
        </tr>
        </thead>
        <tbody>
      {% endif %}
        <tr>
          <td><a href="{{ player.get_absolute_url }}">{{ player.name }}</a></td>
          <td>{{ player.get_sex_display }}</td>
          <td>{{ player.date_of_birth|default:'-' }}</td>
        </tr>
      {% if forloop.last %}
        </tbody>
      </table>
    </div>
    {% endif %}
    {% empty %}
    <div class="mb-2">
      There aren't any players! Add one below.
    </div>
  {% endfor %}
  <div class="mt-2">
    <a class="pg-button-secondary" href="{% url 'teams_example:player_create' request.team.slug %}">
      <span class="pg-icon"><i class="fa fa-plus"></i></span>
      <span>Add Player</span>
    </a>
  </div>
</section>
{% endblock %}